# Site settings
title: "PromptNotes"  # Blog name
author: "PromptNotes"  # Author name
description: "Thoughts on AI, VFX, and the Future of Entertainment"
baseurl: ""  # Leave empty unless your site is in a subdirectory
url: "https://thepromptnotes.github.io"  # GitHub Pages URL

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

# Permalink structure - clean URLs like colah's blog
permalink: /posts/:year/:month/:day/:title/

# Collections for better organization
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Default layout
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins (GitHub Pages supported)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
